# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63c61d8160184d986c6927aaf90b76a855e7c0ae3fa34e6fe38975b5dd2ccb26002e323adc905ea617f1b9efe80aec310e198279c5b522552271ee9101c82d85

test:
  secret_key_base: 48b37911b9a2cb14020cc7123ea42015ee60ede5799c299df2c0e0b3c62e8ece77fd93d085d332ec429b27637f4f1a9a72781638af0ea2e82383d8cda315833f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
